# use Ganache's forked mainnet mode as the default network
networks:
  default: development
  development:
    cmd_settings:
      port: 8545
      accounts: 10
      gas_limit: 12000000
      chain_id: 1
      evm_version: istanbul
#      fork: http://onto-eth.ont.io:10331
      mnemonic: brownie



autofetch_sources: true

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.8.1
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"

reports:
  exclude_paths:
    - contracts/test/Token.sol
  exclude_contracts:
    - SafeMath
    - SafeERC20
    - Address
